"""
Open PR node: Create a new PR with the fix patch.
"""

from src.agent.state import AgentState
from src.utils.github_client import GitHubClient
from datetime import datetime


def open_pr_node(state: AgentState) -> AgentState:
    """
    Create a new pull request on GitHub with the generated fix.
    
    This node:
    1. Uses PyGithub to create a new branch: fix/agent-{pr_number}
    2. Commits the patch with a message
    3. Opens a PR targeting the original PR's base branch
    4. Sets final_status to "fixed"
    
    Args:
        state: Must contain current_patch, pr_number, repo_full_name, pr_base_branch
    
    Returns:
        Updated state with fix_pr_url and final_status set
    """
    
    pr_number = state.get("pr_number", 0)
    iteration = state.get("iteration", 0)
    current_patch = state.get("current_patch", "")
    repo_full_name = state.get("repo_full_name", "")
    pr_base_branch = state.get("pr_base_branch", "main")
    
    if not current_patch or not repo_full_name:
        state["final_status"] = "failed_no_patch"
        return state
    
    try:
        client = GitHubClient()
        
        # Create fix branch name
        fix_branch = f"fix/agent-{pr_number}-iter{iteration}"
        
        # Get current PR head SHA to branch from
        pr = client.get_pr(repo_full_name, pr_number)
        base_sha = pr.head.sha
        
        # Create fix branch
        client.create_fix_branch(
            repo_full_name=repo_full_name,
            base_sha=base_sha,
            new_branch_name=fix_branch,
        )
        
        # TODO: Apply patch to files in the branch
        # For now, store the patch content as a marker file
        commit_msg = f"fix: auto-correction by review agent (iteration {iteration})"
        
        # Open PR from fix branch to base branch
        pr_title = f"[AUTO-FIX] {state.get('pr_title', 'Fix')}"
        pr_body = f"""## Automated Fix Attempt

This PR contains an automated fix for PR #{pr_number}.

**Iterations**: {iteration + 1}
**Status**: ✅ Tests passed

Generated by the self-correcting code review agent.
"""
        
        pr_number_new, pr_url = client.open_pull_request(
            repo_full_name=repo_full_name,
            title=pr_title,
            body=pr_body,
            head_branch=fix_branch,
            base_branch=pr_base_branch,
        )
        
        state["final_status"] = "fixed"
        state["fix_pr_url"] = pr_url
        
        return state
    
    except Exception as e:
        state["final_status"] = "failed_pr_creation"
        state["test_output"] = f"Failed to create PR: {str(e)}"
        return state
