"""
Run Tests node: Execute test suite in isolated Docker sandbox with patch applied.
"""

from src.agent.state import AgentState
from src.utils.docker_sandbox import sandbox_session
import tempfile
import shutil
import os


def run_tests_node(state: AgentState) -> AgentState:
    """
    Apply the current patch to a repository copy and run tests in Docker.
    
    This node:
    1. Creates a temporary copy of the repository
    2. Applies the current_patch using the `patch` command
    3. Spins up a Docker container with resource limits
    4. Installs dependencies and runs pytest
    5. Captures stdout/stderr
    6. Determines if tests passed (exit code 0)
    
    Args:
        state: Must contain current_patch, repo_full_name, iteration
    
    Returns:
        Updated state with test_output and tests_passed populated
    """
    
    current_patch = state.get("current_patch", "")
    repo_full_name = state.get("repo_full_name", "unknown/repo")
    iteration = state.get("iteration", 0)
    
    # If no patch generated, mark as failed
    if not current_patch or current_patch == "CANNOT_FIX":
        state["test_output"] = "No patch generated by LLM"
        state["tests_passed"] = False
        return state
    
    # TODO: In production, clone the actual repo or use a snapshot
    # For demonstration, we show the structure
    
    repo_dir = None
    try:
        # Create temporary directory for repo copy
        repo_dir = tempfile.mkdtemp(prefix=f"sandbox_{iteration}_")
        
        # TODO: Clone/copy actual repo to repo_dir
        # git clone https://github.com/{repo_full_name}.git {repo_dir}
        
        # Run sandbox
        with sandbox_session(
            memory_limit="512m",
            cpu_limit=1.0,
            timeout_seconds=30,
        ) as sandbox:
            sandbox.create_container()
            
            # Copy repo into container
            sandbox.copy_to_container(repo_dir, "/repo")
            
            # Apply patch
            patch_applied, patch_output = sandbox.apply_patch(current_patch)
            if not patch_applied:
                state["test_output"] = f"Failed to apply patch:\n{patch_output}"
                state["tests_passed"] = False
                return state
            
            # Run tests
            tests_passed, test_output = sandbox.run_tests()
            
            state["test_output"] = test_output
            state["tests_passed"] = tests_passed
        
        return state
    
    except Exception as e:
        state["test_output"] = f"Docker execution failed: {str(e)}"
        state["tests_passed"] = False
        return state
    
    finally:
        # Cleanup temp directory
        if repo_dir and os.path.exists(repo_dir):
            shutil.rmtree(repo_dir, ignore_errors=True)
